@startuml

actor User
boundary "DeviceMonitoring\nApplication" as DeviceMonitoringApp
component "DeviceMonitor\n(Presentation Layer)" as DeviceMonitor
component "DeviceDaemon\n(Auditor)" as DeviceDaemon
component "DeviceManager\n(Data Manager)" as DeviceManager
database "MongoDB\n(Database)" as MongoDB

User --> DeviceMonitoringApp
DeviceMonitoringApp --> DeviceMonitor
DeviceMonitoringApp --> DeviceDaemon
DeviceMonitoringApp --> DeviceManager
DeviceMonitoringApp --> MongoDB

DeviceMonitor --> DeviceManager
DeviceDaemon --> DeviceManager
DeviceManager --> MongoDB

@enduml
